# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-13 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='siding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milePost', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milePost', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='yard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milePost', models.IntegerField()),
                ('name', models.CharField(max_length=300)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layoutManagement.station')),
            ],
        ),
        migrations.AddField(
            model_name='siding',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='layoutManagement.station'),
        ),
    ]
