# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-10-06 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=20)),
                ('cartype', models.CharField(max_length=10)),
                ('roadNumber', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Locomotives',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road_name', models.CharField(max_length=20)),
                ('cartype', models.CharField(max_length=10)),
                ('roadNumber', models.CharField(max_length=25)),
            ],
        ),
    ]
